services:
    api:
        container_name: api
        build:
            context: .
            dockerfile: ./.docker/api/Dockerfile
        ports:
            - 8000:8000
        volumes:
            - .:/usr/src/app # TODO: if we are not supposed to do bind mounts, what should we use?
        stdin_open: true
        tty: true
