services:
    api:
        build:
            context: .
            dockerfile: ./.docker/api/Dockerfile
        ports:
            - ${API_PORT}:8000
        volumes:
            - ./backend/static/:/var/www/static
            - ./backend/media/:/var/www/media
            - .:/usr/src/app # TODO: if we are not supposed to do bind mounts, what should we use?
            - ./backend/certs:/usr/src/app/backend/certs
        networks:
            - transcendence
        stdin_open: true
        tty: true
        depends_on:
            - db
            - redis

    db:
        image: postgres
        restart: always
        networks:
            - transcendence
        ports:
            - "${DATABASE_PORT}:5432"
        environment:
            - POSTGRES_DB=${DATABASE_NAME}
            - POSTGRES_PASSWORD=${DATABASE_PASS}
            - POSTGRES_USER=${DATABASE_USER}

    redis:
        image: redis
        restart: always
        networks:
            - transcendence
        ports:
            - "${REDIS_PORT}:6379"

    nginx:
        container_name: nginx
        image: nginx:alpine
        networks:
            - transcendence
        ports:
            - "443:443"
        volumes:
            - ./backend/static/:/var/www/static
            - ./backend/media/:/var/www/media
            - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./backend/certs:/etc/nginx/certs
        restart: on-failure:5
        depends_on:
            - api

networks:
  transcendence:
    name: transcendence
    driver: bridge

