# Generated by Django 4.0 on 2024-07-30 00:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0002_player_groups_player_is_superuser_player_last_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='websocket_channel_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, null=True, size=None),
        ),
    ]
