# Generated by Django 4.0 on 2024-07-30 18:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0003_player_websocket_channel_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='websocket_channel_names',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
    ]
