# Generated by Django 4.0 on 2024-07-30 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0004_alter_player_websocket_channel_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='websocket_channel_names',
        ),
    ]
