# Generated by Django 4.0 on 2024-08-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0005_remove_player_websocket_channel_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='friends',
            field=models.ManyToManyField(blank=True, to='pong.Player'),
        ),
    ]
