# Generated by Django 4.0 on 2024-08-05 19:25

from django.db import migrations, models
import pong.models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0006_player_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='avatar',
            field=models.ImageField(blank=True, default='/default/player/avatar/default.jpg', upload_to=pong.models.playerAvatarPath),
        ),
    ]
