# Generated by Django 4.0 on 2024-08-09 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0008_alter_player_email_message_chat_player_blocked_chats'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='activity_status',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], default='OFFLINE', max_length=20),
        ),
    ]
