# Generated by Django 4.2 on 2024-08-15 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0010_match_created_at_match_updated_at_match_winner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='brackets',
        ),
        migrations.AddField(
            model_name='match',
            name='child_lower',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_lower', to='pong.match'),
        ),
        migrations.AddField(
            model_name='match',
            name='child_upper',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_upper', to='pong.match'),
        ),
        migrations.AddField(
            model_name='match',
            name='max',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Criado'), ('AWAITING_CONFIRMATION', 'Aguardando Confirmação'), ('IN_PROGRESS', 'Em Progresso'), ('FINISHED', 'Finalizado')], default='CREATED', max_length=20),
        ),
        migrations.AddField(
            model_name='tournament',
            name='root_match',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pong.match'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Criado'), ('IN_PROGRESS', 'Em Progresso'), ('FINISHED', 'Finalizado')], default='CREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TournamentBracket',
        ),
    ]
