# Generated by Django 4.2 on 2024-08-16 19:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0011_remove_tournament_brackets_match_child_lower_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='accepted_players',
            field=models.ManyToManyField(blank=True, related_name='accepted_players', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='match',
            name='rejected_players',
            field=models.ManyToManyField(blank=True, related_name='rejected_players', to=settings.AUTH_USER_MODEL),
        ),
    ]
