# Generated by Django 4.2 on 2024-08-17 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0012_match_accepted_players_match_rejected_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='accepted_players',
            field=models.ManyToManyField(blank=True, related_name='tournament_accepted_players', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournament',
            name='players',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tournament',
            name='rejected_players',
            field=models.ManyToManyField(blank=True, related_name='tournement_rejected_players', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Criado'), ('AWAITING_CONFIRMATION', 'Aguardando Confirmação'), ('IN_PROGRESS', 'Em Progresso'), ('FINISHED', 'Finalizado'), ('CANCELLED', 'Cancelado')], default='CREATED', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='champion',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='champion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Criado'), ('AWAITING_CONFIRMATION', 'Aguardando Confirmação'), ('IN_PROGRESS', 'Em Progresso'), ('FINISHED', 'Finalizado'), ('CANCELLED', 'Cancelado')], default='CREATED', max_length=20),
        ),
    ]
